"""create user, portfolio, holding, backtest_result tables

Revision ID: 30594d39da38
Revises:
Create Date: 2026-06-06 07:14:13.220025

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30594d39da38"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("default_portfolio_id", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "portfolios",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("benchmark_ticker", sa.String(length=16), server_default="SPY", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolios_user_id"), "portfolios", ["user_id"], unique=False)
    # `users.default_portfolio_id` -> `portfolios.id` is a circular FK (users is
    # created first), so it's added here as a separate ALTER TABLE rather than
    # inline on `create_table('users', ...)`. Autogenerate emits `use_alter=True`
    # FKs inline, where Alembic's `op.create_table` silently drops them instead
    # of deferring — this constraint must be added explicitly post-table-creation.
    op.create_foreign_key(
        "fk_users_default_portfolio_id",
        "users",
        "portfolios",
        ["default_portfolio_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("strategy_name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "rebalance_frequency",
            sa.Enum("MONTHLY", "QUARTERLY", "ANNUALLY", "NEVER", name="rebalance_frequency"),
            nullable=False,
        ),
        sa.Column("initial_investment", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("tearsheet", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("daily_returns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("equity_curve", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_results_portfolio_id"), "backtest_results", ["portfolio_id"], unique=False
    )
    op.create_table(
        "holdings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("portfolio_id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("asset_name", sa.String(length=255), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum(
                "EQUITY", "FIXED_INCOME", "REAL_ESTATE", "COMMODITY", "CASH", name="asset_class"
            ),
            nullable=False,
        ),
        sa.Column("target_weight", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column("current_shares", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holdings_portfolio_id"), "holdings", ["portfolio_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_holdings_portfolio_id"), table_name="holdings")
    op.drop_table("holdings")
    op.drop_index(op.f("ix_backtest_results_portfolio_id"), table_name="backtest_results")
    op.drop_table("backtest_results")
    op.drop_index(op.f("ix_portfolios_user_id"), table_name="portfolios")
    op.drop_constraint("fk_users_default_portfolio_id", "users", type_="foreignkey")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
    # `DROP TABLE` does not drop the native Postgres ENUM types `create_table`
    # implicitly created for the `asset_class`/`rebalance_frequency` columns —
    # left behind, they collide with `CREATE TYPE` on the next `upgrade`.
    sa.Enum(name="asset_class").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="rebalance_frequency").drop(op.get_bind(), checkfirst=True)
